/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as ClubTeamslugRouteRouteImport } from './routes/club/$teamslug/route'
import { Route as ClubTeamslugSignupRouteImport } from './routes/club/$teamslug/signup'
import { Route as ClubTeamslugSigninRouteImport } from './routes/club/$teamslug/signin'
import { Route as ClubTeamslugDashboardRouteImport } from './routes/club/$teamslug/dashboard'
import { Route as ClubTeamslugstorefrontRouteRouteImport } from './routes/club/$teamslug/(storefront)/route'
import { Route as ClubTeamslugstorefrontSponsorshipsRouteImport } from './routes/club/$teamslug/(storefront)/sponsorships'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const ClubTeamslugRouteRoute = ClubTeamslugRouteRouteImport.update({
  id: '/club/$teamslug',
  path: '/club/$teamslug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubTeamslugSignupRoute = ClubTeamslugSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => ClubTeamslugRouteRoute,
} as any)
const ClubTeamslugSigninRoute = ClubTeamslugSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => ClubTeamslugRouteRoute,
} as any)
const ClubTeamslugDashboardRoute = ClubTeamslugDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClubTeamslugRouteRoute,
} as any)
const ClubTeamslugstorefrontRouteRoute =
  ClubTeamslugstorefrontRouteRouteImport.update({
    id: '/(storefront)',
    getParentRoute: () => ClubTeamslugRouteRoute,
  } as any)
const ClubTeamslugstorefrontSponsorshipsRoute =
  ClubTeamslugstorefrontSponsorshipsRouteImport.update({
    id: '/sponsorships',
    path: '/sponsorships',
    getParentRoute: () => ClubTeamslugstorefrontRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/club/$teamslug': typeof ClubTeamslugstorefrontRouteRouteWithChildren
  '/about': typeof publicAboutRoute
  '/': typeof publicIndexRoute
  '/club/$teamslug/dashboard': typeof ClubTeamslugDashboardRoute
  '/club/$teamslug/signin': typeof ClubTeamslugSigninRoute
  '/club/$teamslug/signup': typeof ClubTeamslugSignupRoute
  '/club/$teamslug/sponsorships': typeof ClubTeamslugstorefrontSponsorshipsRoute
}
export interface FileRoutesByTo {
  '/club/$teamslug': typeof ClubTeamslugstorefrontRouteRouteWithChildren
  '/about': typeof publicAboutRoute
  '/': typeof publicIndexRoute
  '/club/$teamslug/dashboard': typeof ClubTeamslugDashboardRoute
  '/club/$teamslug/signin': typeof ClubTeamslugSigninRoute
  '/club/$teamslug/signup': typeof ClubTeamslugSignupRoute
  '/club/$teamslug/sponsorships': typeof ClubTeamslugstorefrontSponsorshipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/club/$teamslug': typeof ClubTeamslugRouteRouteWithChildren
  '/(public)/about': typeof publicAboutRoute
  '/(public)/': typeof publicIndexRoute
  '/club/$teamslug/(storefront)': typeof ClubTeamslugstorefrontRouteRouteWithChildren
  '/club/$teamslug/dashboard': typeof ClubTeamslugDashboardRoute
  '/club/$teamslug/signin': typeof ClubTeamslugSigninRoute
  '/club/$teamslug/signup': typeof ClubTeamslugSignupRoute
  '/club/$teamslug/(storefront)/sponsorships': typeof ClubTeamslugstorefrontSponsorshipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/club/$teamslug'
    | '/about'
    | '/'
    | '/club/$teamslug/dashboard'
    | '/club/$teamslug/signin'
    | '/club/$teamslug/signup'
    | '/club/$teamslug/sponsorships'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/club/$teamslug'
    | '/about'
    | '/'
    | '/club/$teamslug/dashboard'
    | '/club/$teamslug/signin'
    | '/club/$teamslug/signup'
    | '/club/$teamslug/sponsorships'
  id:
    | '__root__'
    | '/(public)'
    | '/club/$teamslug'
    | '/(public)/about'
    | '/(public)/'
    | '/club/$teamslug/(storefront)'
    | '/club/$teamslug/dashboard'
    | '/club/$teamslug/signin'
    | '/club/$teamslug/signup'
    | '/club/$teamslug/(storefront)/sponsorships'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ClubTeamslugRouteRoute: typeof ClubTeamslugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/club/$teamslug': {
      id: '/club/$teamslug'
      path: '/club/$teamslug'
      fullPath: '/club/$teamslug'
      preLoaderRoute: typeof ClubTeamslugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$teamslug/signup': {
      id: '/club/$teamslug/signup'
      path: '/signup'
      fullPath: '/club/$teamslug/signup'
      preLoaderRoute: typeof ClubTeamslugSignupRouteImport
      parentRoute: typeof ClubTeamslugRouteRoute
    }
    '/club/$teamslug/signin': {
      id: '/club/$teamslug/signin'
      path: '/signin'
      fullPath: '/club/$teamslug/signin'
      preLoaderRoute: typeof ClubTeamslugSigninRouteImport
      parentRoute: typeof ClubTeamslugRouteRoute
    }
    '/club/$teamslug/dashboard': {
      id: '/club/$teamslug/dashboard'
      path: '/dashboard'
      fullPath: '/club/$teamslug/dashboard'
      preLoaderRoute: typeof ClubTeamslugDashboardRouteImport
      parentRoute: typeof ClubTeamslugRouteRoute
    }
    '/club/$teamslug/(storefront)': {
      id: '/club/$teamslug/(storefront)'
      path: ''
      fullPath: '/club/$teamslug'
      preLoaderRoute: typeof ClubTeamslugstorefrontRouteRouteImport
      parentRoute: typeof ClubTeamslugRouteRoute
    }
    '/club/$teamslug/(storefront)/sponsorships': {
      id: '/club/$teamslug/(storefront)/sponsorships'
      path: '/sponsorships'
      fullPath: '/club/$teamslug/sponsorships'
      preLoaderRoute: typeof ClubTeamslugstorefrontSponsorshipsRouteImport
      parentRoute: typeof ClubTeamslugstorefrontRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface ClubTeamslugstorefrontRouteRouteChildren {
  ClubTeamslugstorefrontSponsorshipsRoute: typeof ClubTeamslugstorefrontSponsorshipsRoute
}

const ClubTeamslugstorefrontRouteRouteChildren: ClubTeamslugstorefrontRouteRouteChildren =
  {
    ClubTeamslugstorefrontSponsorshipsRoute:
      ClubTeamslugstorefrontSponsorshipsRoute,
  }

const ClubTeamslugstorefrontRouteRouteWithChildren =
  ClubTeamslugstorefrontRouteRoute._addFileChildren(
    ClubTeamslugstorefrontRouteRouteChildren,
  )

interface ClubTeamslugRouteRouteChildren {
  ClubTeamslugstorefrontRouteRoute: typeof ClubTeamslugstorefrontRouteRouteWithChildren
  ClubTeamslugDashboardRoute: typeof ClubTeamslugDashboardRoute
  ClubTeamslugSigninRoute: typeof ClubTeamslugSigninRoute
  ClubTeamslugSignupRoute: typeof ClubTeamslugSignupRoute
}

const ClubTeamslugRouteRouteChildren: ClubTeamslugRouteRouteChildren = {
  ClubTeamslugstorefrontRouteRoute:
    ClubTeamslugstorefrontRouteRouteWithChildren,
  ClubTeamslugDashboardRoute: ClubTeamslugDashboardRoute,
  ClubTeamslugSigninRoute: ClubTeamslugSigninRoute,
  ClubTeamslugSignupRoute: ClubTeamslugSignupRoute,
}

const ClubTeamslugRouteRouteWithChildren =
  ClubTeamslugRouteRoute._addFileChildren(ClubTeamslugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  ClubTeamslugRouteRoute: ClubTeamslugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
