/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as storefrontRouteRouteImport } from './routes/(storefront)/route'
import { Route as storefrontIndexRouteImport } from './routes/(storefront)/index'
import { Route as storefrontAboutRouteImport } from './routes/(storefront)/about'
import { Route as FormsClubSignupRouteImport } from './routes/_forms/club/signup'
import { Route as FormsClubSigninRouteImport } from './routes/_forms/club/signin'
import { Route as FormsClubDashboardRouteImport } from './routes/_forms/club/dashboard'
import { Route as storefrontclubSponsorshipsRouteImport } from './routes/(storefront)/(club)/sponsorships'

const storefrontRouteRoute = storefrontRouteRouteImport.update({
  id: '/(storefront)',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontIndexRoute = storefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const storefrontAboutRoute = storefrontAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const FormsClubSignupRoute = FormsClubSignupRouteImport.update({
  id: '/_forms/club/signup',
  path: '/club/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsClubSigninRoute = FormsClubSigninRouteImport.update({
  id: '/_forms/club/signin',
  path: '/club/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsClubDashboardRoute = FormsClubDashboardRouteImport.update({
  id: '/_forms/club/dashboard',
  path: '/club/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontclubSponsorshipsRoute =
  storefrontclubSponsorshipsRouteImport.update({
    id: '/(club)/sponsorships',
    path: '/sponsorships',
    getParentRoute: () => storefrontRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/about': typeof storefrontAboutRoute
  '/': typeof storefrontIndexRoute
  '/sponsorships': typeof storefrontclubSponsorshipsRoute
  '/club/dashboard': typeof FormsClubDashboardRoute
  '/club/signin': typeof FormsClubSigninRoute
  '/club/signup': typeof FormsClubSignupRoute
}
export interface FileRoutesByTo {
  '/about': typeof storefrontAboutRoute
  '/': typeof storefrontIndexRoute
  '/sponsorships': typeof storefrontclubSponsorshipsRoute
  '/club/dashboard': typeof FormsClubDashboardRoute
  '/club/signin': typeof FormsClubSigninRoute
  '/club/signup': typeof FormsClubSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(storefront)': typeof storefrontRouteRouteWithChildren
  '/(storefront)/about': typeof storefrontAboutRoute
  '/(storefront)/': typeof storefrontIndexRoute
  '/(storefront)/(club)/sponsorships': typeof storefrontclubSponsorshipsRoute
  '/_forms/club/dashboard': typeof FormsClubDashboardRoute
  '/_forms/club/signin': typeof FormsClubSigninRoute
  '/_forms/club/signup': typeof FormsClubSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/'
    | '/sponsorships'
    | '/club/dashboard'
    | '/club/signin'
    | '/club/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/'
    | '/sponsorships'
    | '/club/dashboard'
    | '/club/signin'
    | '/club/signup'
  id:
    | '__root__'
    | '/(storefront)'
    | '/(storefront)/about'
    | '/(storefront)/'
    | '/(storefront)/(club)/sponsorships'
    | '/_forms/club/dashboard'
    | '/_forms/club/signin'
    | '/_forms/club/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  storefrontRouteRoute: typeof storefrontRouteRouteWithChildren
  FormsClubDashboardRoute: typeof FormsClubDashboardRoute
  FormsClubSigninRoute: typeof FormsClubSigninRoute
  FormsClubSignupRoute: typeof FormsClubSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(storefront)': {
      id: '/(storefront)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)/': {
      id: '/(storefront)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storefrontIndexRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/about': {
      id: '/(storefront)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof storefrontAboutRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/_forms/club/signup': {
      id: '/_forms/club/signup'
      path: '/club/signup'
      fullPath: '/club/signup'
      preLoaderRoute: typeof FormsClubSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_forms/club/signin': {
      id: '/_forms/club/signin'
      path: '/club/signin'
      fullPath: '/club/signin'
      preLoaderRoute: typeof FormsClubSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_forms/club/dashboard': {
      id: '/_forms/club/dashboard'
      path: '/club/dashboard'
      fullPath: '/club/dashboard'
      preLoaderRoute: typeof FormsClubDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)/(club)/sponsorships': {
      id: '/(storefront)/(club)/sponsorships'
      path: '/sponsorships'
      fullPath: '/sponsorships'
      preLoaderRoute: typeof storefrontclubSponsorshipsRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
  }
}

interface storefrontRouteRouteChildren {
  storefrontAboutRoute: typeof storefrontAboutRoute
  storefrontIndexRoute: typeof storefrontIndexRoute
  storefrontclubSponsorshipsRoute: typeof storefrontclubSponsorshipsRoute
}

const storefrontRouteRouteChildren: storefrontRouteRouteChildren = {
  storefrontAboutRoute: storefrontAboutRoute,
  storefrontIndexRoute: storefrontIndexRoute,
  storefrontclubSponsorshipsRoute: storefrontclubSponsorshipsRoute,
}

const storefrontRouteRouteWithChildren = storefrontRouteRoute._addFileChildren(
  storefrontRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  storefrontRouteRoute: storefrontRouteRouteWithChildren,
  FormsClubDashboardRoute: FormsClubDashboardRoute,
  FormsClubSigninRoute: FormsClubSigninRoute,
  FormsClubSignupRoute: FormsClubSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
