/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as storefrontRouteRouteImport } from './routes/(storefront)/route'
import { Route as storefrontIndexRouteImport } from './routes/(storefront)/index'
import { Route as storefrontClubRouteImport } from './routes/(storefront)/club'
import { Route as storefrontAboutRouteImport } from './routes/(storefront)/about'
import { Route as RegisterClubSignupRouteImport } from './routes/_forms/club/signup'

const storefrontRouteRoute = storefrontRouteRouteImport.update({
  id: '/(storefront)',
  getParentRoute: () => rootRouteImport,
} as any)
const storefrontIndexRoute = storefrontIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const storefrontClubRoute = storefrontClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const storefrontAboutRoute = storefrontAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => storefrontRouteRoute,
} as any)
const RegisterClubSignupRoute = RegisterClubSignupRouteImport.update({
  id: '/_register/club/signup',
  path: '/club/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof storefrontAboutRoute
  '/club': typeof storefrontClubRoute
  '/': typeof storefrontIndexRoute
  '/club/signup': typeof RegisterClubSignupRoute
}
export interface FileRoutesByTo {
  '/about': typeof storefrontAboutRoute
  '/club': typeof storefrontClubRoute
  '/': typeof storefrontIndexRoute
  '/club/signup': typeof RegisterClubSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(storefront)': typeof storefrontRouteRouteWithChildren
  '/(storefront)/about': typeof storefrontAboutRoute
  '/(storefront)/club': typeof storefrontClubRoute
  '/(storefront)/': typeof storefrontIndexRoute
  '/_register/club/signup': typeof RegisterClubSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/club' | '/' | '/club/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/club' | '/' | '/club/signup'
  id:
    | '__root__'
    | '/(storefront)'
    | '/(storefront)/about'
    | '/(storefront)/club'
    | '/(storefront)/'
    | '/_register/club/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  storefrontRouteRoute: typeof storefrontRouteRouteWithChildren
  RegisterClubSignupRoute: typeof RegisterClubSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(storefront)': {
      id: '/(storefront)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof storefrontRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(storefront)/': {
      id: '/(storefront)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof storefrontIndexRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/club': {
      id: '/(storefront)/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof storefrontClubRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/(storefront)/about': {
      id: '/(storefront)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof storefrontAboutRouteImport
      parentRoute: typeof storefrontRouteRoute
    }
    '/_register/club/signup': {
      id: '/_register/club/signup'
      path: '/club/signup'
      fullPath: '/club/signup'
      preLoaderRoute: typeof RegisterClubSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface storefrontRouteRouteChildren {
  storefrontAboutRoute: typeof storefrontAboutRoute
  storefrontClubRoute: typeof storefrontClubRoute
  storefrontIndexRoute: typeof storefrontIndexRoute
}

const storefrontRouteRouteChildren: storefrontRouteRouteChildren = {
  storefrontAboutRoute: storefrontAboutRoute,
  storefrontClubRoute: storefrontClubRoute,
  storefrontIndexRoute: storefrontIndexRoute,
}

const storefrontRouteRouteWithChildren = storefrontRouteRoute._addFileChildren(
  storefrontRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  storefrontRouteRoute: storefrontRouteRouteWithChildren,
  RegisterClubSignupRoute: RegisterClubSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
